services:
  opencv-python-server:
    container_name: opencv-python-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_HOST=localhost
      # - SPRING_HOST=java-spring-server
      - SPRING_PORT=8080
      - DEBUG=False
      - CR_PORT=8081
    networks:
      - tfo-net
    ports:
      - 8081:8081
    restart: always

networks:
  tfo-net:
    external: true