services:
  opencv-python-server:
    container_name: opencv-python-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_HOST=java-spring-server
      - SPRIN_PORT=8080
    networks:
      - tfo-net
    ports:
      - 8081:8081
    restart: always

networks:
  tfo-net:
    external: true